README.md

Put the extension `md` to allow GitHub to identify the file and transform it to HTML, improving the presentation of the project. Formatted the file to markdown. Put links to references.

Formatted the readme file

---

src/bin/jp2/convert.c
src/bin/jp2/convert.h
src/bin/jp2/opj_decompress.c
src/lib/openjp2/j2k.c
tests/conformance/CMakeLists.txt

Add option to force component splitting in imagetopnm

---

src/lib/openjp2/j2k.c

Okay, so this is my very first pull request, removing the apparently superfluous call in line 10024 opj_alloc_tile_component_data(l_tilec);
I tested this manually and reran the regression tests encountering no apparent differences. Please be gentle on feedback as I'm quite new to collaborating on github.

fix Suspicious code in j2k.c #517

---

src/lib/openjp2/j2k.c
src/lib/openjp2/j2k.h

Update uclouvain/openjpeg#470
Update uclouvain/openjpeg#288
Update uclouvain/openjpeg#532

Refactor opj_j2k_read_ppm & opj_j2k_read_ppt

---

src/lib/openjp2/cio.c

This patch, originally by @szukw000, fixes the issue where opj_compress + opj_decompress fails on bigendian systems.

Fix opj_write_bytes_BE (#518)

---

src/bin/jp2/convert.c
src/bin/jp2/convertbmp.c
src/bin/jp2/convertpng.c
src/bin/jp2/converttif.c
src/bin/jp2/opj_compress.c
src/bin/jp2/opj_decompress.c
src/lib/openjp2/cio.c
src/lib/openjp2/j2k.c
src/lib/openjp2/opj_includes.h
src/lib/openjp2/opj_intmath.h
src/lib/openjp2/pi.c
src/lib/openjp2/tcd.c

Remove some warnings when building

---

cmake/FindJPYLYZER.cmake
tests/nonregression/CMakeLists.txt

This will help to guarantee that OpenJpeg generates valid JP2 files.

Add jpylyzer tests for JP2 compression

---

src/bin/common/color.c
src/bin/common/color.h
src/bin/jp2/opj_decompress.c
src/lib/openjp2/jp2.c

Declares three new functions
Calls the three new functions
Collects data for CIELab, sets the color_space for EYCC and CMYK

Add support for CIELab, EYCC and CMYK

---

src/lib/openjp2/tcd.c
tests/compare_images.c
tests/nonregression/CMakeLists.txt
tests/nonregression/test_suite.ctest.in

Correct lossless issue on linux x86

---

src/lib/openjp2/j2k.c
src/lib/openjp2/jp2.c

I'm compiling the OpenJPEG source also with the .NET C++ compiler. In a few places the casts for the return values of opj_malloc()/opj_calloc() are missing, which prevents successful compilation in C++ mode. As the casts for the return values of opj_malloc()/opj_calloc() are present otherwise in the rest of the OpenJPEG source code, I guess the missing casts were left out by accident.

Added missing casts for return values of opj_malloc()/opj_calloc().

---

src/lib/openjp2/cio.c
src/lib/openjp2/cio.h

Replaced usage of an enum typedef for a variable that is used
for bit flags with OPJ_UINT32 type.

Fixed problem that C++ compilation failed because of enum variable.

---

src/bin/common/opj_getopt.c
src/bin/jp2/convertpng.c
src/bin/jp2/converttif.c
src/bin/jp2/opj_decompress.c
src/bin/jp2/opj_dump.c

g++ complains about invalid conversions like these ones:
error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
error: invalid conversion from ‘void*’ to ‘opj_precision* {aka opj_prec*}’ [-fpermissive]

Fix warnings for C++

---

src/lib/openjp2/opj_clock.c

"opj_includes.h" must be included before system headers, otherwise
inconsistent definitions of configuration macros lead to build
failures on AIX.

Fix OpenJPEG GitHub issue #633.

---

CMakeLists.txt
INSTALL

The data is now maintained in a git repository on Github.

Fix repository for JPEG2000 test data

---

src/lib/openjp2/dwt.c
src/lib/openjp2/t2.c

HP compiler warns:
cc: "dwt.c", line 798: warning 562: Redeclaration of "opj_v4dwt_decode"
with a different storage class specifier: "opj_v4dwt_decode" will have
internal linkage.
cc: "t2.c", line 1341: warning 562: Redeclaration of "opj_t2_init_seg"
with a different storage class specifier: "opj_t2_init_seg" will have
internal linkage.
Fix for issue #640.

Fix HP compiler warning about redeclaration of function (#640)

---

src/lib/openjp2/opj_malloc.c

Taking the difference of two void * pointers is not defined according to the C specification, and for example the z/OS compiler warns:
./opj_malloc.c:169   Operation between types `void*` and `void*` is not allowed.

Avoid pointer arithmetic with (void *) pointers

---

src/bin/jp2/convert.c

The static code analyzer cppcheck warns about unsigned integers
which use "%d" in the format string.
It also warns about an unneeded assignment.
Fix both issues.

Fix format strings and unneeded assignment

---

src/lib/openjp2/jp2.c

Fix typo in comments

---

src/bin/jp2/opj_decompress.c

The png format is also supported, so add it to the message.
Remove also the unneeded blank character before \n.

opj_decompress: Update error message

---

src/lib/openjp2/j2k.c
src/lib/openjp2/pi.c
src/lib/openmj2/mj2.h

Fix duplicate article in comments

---

src/lib/openjp2/dwt.c

When trying the GDAL OpenJPEG driver against openjpeg current master HEAD,
I get failures when trying to create .jp2 files. The driver uses
opj_write_tile() and in some tests numresolutions = 1.
In openjp2/dwt.c:410, l_data_size = opj_dwt_max_resolution( tilec->resolutions,tilec->numresolutions) * (OPJ_UINT32)sizeof(OPJ_INT32);
is called and returns l_data_size = 0. Now in git opj_malloc() has a special case
for 0 to return a NULL pointer whereas previously it relied on system malloc(),
which in my case didn't return NULL.
So only test the pointer value if l_data_size != 0. This makes the GDAL
autotest suite to pass again.

[git/2.1 regression] Fix opj_write_tile() failure when numresolutions=1

---

CMakeLists.txt
src/lib/openjp2/opj_config_private.h.cmake.in

posix_memalloc is only declared conditionally in stdlib.h,
so add one of the possible definitions to get the declaration.

Fix support of posix_memalloc for Linux

---

src/bin/jp2/opj_dump.c

The variables defined here are not used anywhere in the code, even in ifdef'd code.
They create a cppcheck warning. Better to get rid of them

Remove dead code in opj_dump

---

src/lib/openjp2/mqc.c

issue #695 MQ Encode: ensure that bp pointer never points to uninitialized memory

---

src/lib/openjp2/t1.c

As @boxerab said, this shall have no performance impact on 2’s complement machine where
the compiler generates a left shift instruction for the signed multiplication by a positive constant power of two.
Verified at least on MacOS Xcode 7.3, same assembly generated after fix.
Update #718

Fix negative shift left reported by UBSan

---

src/lib/openjp2/tcd.c

Fix unsigned int overflow reported by UBSan

---

src/bin/jp2/index.c
src/lib/openjp2/j2k.c
src/lib/openjp2/tcd.c

clang reports a number of implicit float-to-bool conversions.

Fix implicit floating bool conversion

---

src/lib/openjp2/j2k.c
tests/nonregression/CMakeLists.txt

Check SSIZ is valid in opj_j2k_read_siz

---

src/bin/common/color.c

When all components do not have the same dx/dy, components buffer are
read beyond their end.
Do not convert in this case.
Update #725

Fix heap-buffer-overflow in color_esycc_to_rgb

---

src/bin/common/color.c
src/bin/jp2/convertbmp.c

422 Images with an odd x0 lead to subsampled component starting at the 2nd column.
That is offset = comp->dx * comp->x0 - image->x0 = 1
Update uclouvain/openjpeg#726

Fix Out-Of-Bounds Read in sycc42x_to_rgb function

---

cmake/CTestCustom.cmake.in

This assumes prior text has matched some other warning expression.
This reduces the warnings reported for clang build on the dashboard,
which were caused only by the "XXX warnings generated." message.
For some reason they were not reported when not using ctest launchers.
This commit allows to confidently use ctest launchers to improve
dashboard reports.

Ignore clang's summary warning

---

src/lib/openjpip/CMakeLists.txt

They all need opj_malloc and other functions from opc_malloc.c.

Add missing source for the JPIP library and executables (issue #658)

---

src/lib/openjp2/opj_malloc.c

The parameter "size" is typically the size of some data type and should
never be 0. It is much more important to check the "num" parameter if
defined behaviour is required.
Remove also a comment which is not helpful.

Fix implementation of opj_calloc

---

src/lib/openjpip/libopenjpip.pc.cmake.in
src/lib/openjpwl/libopenjpwl.pc.cmake.in

openjpeg provides libopenjp2.pc, so the require statements must refer to
libopenjp2 instead of openjp2.

Fix dependency for pkg-config (issue #594)

---

src/bin/jpwl/convert.c

The type casts which used this data type can be removed by changing
the signature of function swap16. As this function is called with
unsigned variables, this change is reasonable.

jpwl: Remove non-portable data type u_int16_t (fix issue #796)

---

tests/CMakeLists.txt
tests/include_openjpeg.c

This ensures all openjpeg.h dependencies are met.
Update uclouvain/openjpeg#673

Add compilation test for standalone inclusion of openjpeg.h

---

.travis.yml
tools/travis-ci/install.sh

Seems clang is back online & now available through apt add-on 
If the PR passes test, this will be confirmed.

Reenable clang-3.9 build on travis

---

.travis.yml

clang 3.9 is currently unavailable for precise through apt

Switch to clang 3.8

---

src/lib/openjp2/dwt.c
src/lib/openjp2/dwt.h
src/lib/openjp2/mct.c
src/lib/openjp2/mct.h
src/lib/openjp2/opj_includes.h
src/lib/openjp2/t1.c

Do not define reserved keywords.
Same as #661 (which can't be merged anymore)

Change 'restrict' define to 'OPJ_RESTRICT'

---

src/lib/openjp2/jp2.c

In case multiple ihdr box are present, only the first one shall be
taken into account.

Fix leak & invalid behavior of opj_jp2_read_ihdr

---

src/lib/openjp2/pi.c

Prevent an integer overflow issue in function opj_pi_create_decode of
pi.c.
Hi, I found an integer overflow issue which could lead to OOB read and OOB write. I'd like to submit the proof-of-concept file and vulnerability report privately. Please give me an email address to report this issue. Thanks.
Regards,
Ke Liu of Tencent's Xuanwu LAB

Fix an integer overflow issue

---

src/lib/openjp2/tcd.c
tests/compare_dump_files.c
tests/nonregression/test_suite.ctest.in

Coordinates are casted from OPJ_UINT32 to OPJ_INT32
Add sanity check for negative values and upper bound becoming lower
than lower bound.
See also
https://pdfium.googlesource.com/pdfium/+/b6befb2ed2485a3805cddea86dc7574510178ea9

Add sanity check for tile coordinates

---

src/lib/openjp2/t1_generate_luts.c

@detonin,
I'm almost sure the fall through is intentional otherwise nothing would work but, just to be sure, can you confirm ?
The added comment will tell coverity not to report an issue & the code will be clearer for everyone.

Fix coverity 113065 (CWE-484)

---

src/lib/openjp2/j2k.h
src/lib/openjp2/openjpeg.h
src/lib/openjp2/opj_includes.h
src/lib/openjp2/tcd.h

The definition of bit-fields with type OPJ_UINT32 caused compilation errors
on IBM iSeries, because OPJ_UINT32 is defined as uint32_t, and
uint32_t is defined as unsigned long in `<stdint.h>` on IBM iSeries:
228       |typedef struct opj_simple_mcc_decorrelation_data                                                  
229       |{                                                                                                
230       | OPJ_UINT32    m_index;                                                                          
231       | OPJ_UINT32    m_nb_comps;                                                                       
232       | opj_mct_data_t *  m_decorrelation_array;                                                        
233       | opj_mct_data_t *  m_offset_array; …

Bit fields type

---

src/lib/openjp2/dwt.c
src/lib/openjp2/pi.c
src/lib/openjp2/t1.c

See
https://pdfium.googlesource.com/pdfium/+/b20ab6c7acb3be1393461eb650ca8fa4660c937e/third_party/libopenjpeg20/0020-opj_aligned_malloc.patch

Add overflow checks for opj_aligned_malloc

---

src/lib/openjp2/dwt.c

The check was already done. It’s been simplified.
Reformat to get consistent style throughout the functions.

Remove TODO for overflow check

---

src/lib/openjpip/jpip_parser.c
src/lib/openjpip/query_parser.c

Fix potential out-of-bounds read (coverity) 

---

src/lib/openjpip/j2kheader_manager.c
tests/test_tile_decoder.c
tests/test_tile_encoder.c

Fix some issues reported by Coverity Scan

---

src/bin/jp2/convert.c
tests/nonregression/test_suite.ctest.in

Malformed PNM file could cause a crash in opj_compress.
Checks were added to prevent this.
Fixes #843
Updates #440

Fix PNM file reading

---

README.md

You can see the fixed version here: https://github.com/alexwlchan/openjpeg/tree/fix-readme

Escape quotes to ensure README renders on GitHub correctly

---

doc/man/man1/opj_compress.1
doc/man/man1/opj_decompress.1

Fixes the following warnings from `man`:
```
`R' is a string (producing the registered sign), not a macro.
```

Remove spurious .R macros from manpages

---

src/lib/openjp2/tcd.c
src/lib/openjp2/tgt.c

Decoding some valid .jp2 files like Sentinel2 datasets leads to warnings like:
No incltree created.
tgt_create tree->numnodes == 0, no tree created.
No imsbtree created.
tgt_create tree->numnodes == 0, no tree created.
Besides that, the image is correctly decoded. So there is no reason to emit
those warnings.

Remove warnings related to empty tag-trees.

---

.travis.yml
tests/performance/compare_perfs.py
tests/performance/perf_test.py
tests/performance/perf_test_filelist.csv
tools/travis-ci/run.sh

And run them by Travis-CI
Note: I've some doubt about the reproductibility and trustability in those tests on Travis infrastructure. Initially I had tried them on OSX workers too but this seemed far too unreliable : https://travis-ci.org/rouault/openjpeg/jobs/228744947
This relates to #911

Add performance benchmarking scripts

---

.travis.yml
tests/profiling/filter_massif_output.py
tools/travis-ci/run.sh

Extract from https://travis-ci.org/rouault/openjpeg/jobs/229438863 output :
```
Most CPU consuming functions:
Flat profile:
Each sample counts as 0.01 seconds.
%   cumulative   self              self     total           
time   seconds   seconds    calls  ms/call  ms/call  name    
29.85      0.20     0.20 15312165     0.00     0.00  opj_mqc_decode
23.88      0.36     0.16    30595     0.01     0.01  opj_t1_dec_clnpass_generic
14.93      0.46     0.10     9768     0.01     0.06  opj_t1_clbl_decode_processor
11.94      0.54     0.08    24359     0.00     0.01  opj_t1_dec_refpass_mqc_generic
4.48      0.57     0.03        3    10.00    13.33  opj_dwt_decode_real
Memory consumption profile:
n5: 182030675 (heap allocation functions) malloc/new/new[], --alloc-fns, etc.
n2: 81687952 0x4E70F84: …
```

Add profiling of CPU and memory usage (#912)

---

src/lib/openjp2/mqc.c
src/lib/openjp2/mqc.h
src/lib/openjp2/t1.c
src/lib/openjp2/t2.c
src/lib/openjp2/tcd.c
src/lib/openjp2/tcd.h
tests/nonregression/test_suite.ctest.in

Although techically independant, for conveniency (new test cases added), this is on top of the earlier PR https://github.com/uclouvain/openjpeg/pull/947 for BYPASS and TERMALL fixes

Fix bypass pterm termall and lossless decomposition issue (#891, #892)

---

src/bin/jp2/opj_decompress.c

This is a possible solution to uclouvain/openjpeg#130 
This adds a new -quiet long parameter, and checks that parameter before writing to stdout.
I adjusted one error to write to stderr rather than stdout.
I only modified opj_decompress as I have a specific need for this command to have a quiet mode.
Please adjust for code style/etc.  I haven't written any C in over a decade...

Quiet mode for opj_decompress via -quiet long parameter.

---

src/lib/openjp2/bio.c

Commit 29313eb5 introduced those flags to avoid issues with
-fsanitize=unsigned-integer-overflow
However it is better just to rewrite the loop to avoid such condition
to occur.

Remove OPJ_NOSANITIZE in opj_bio_read() and opj_bio_write() (#761)

---

.travis.yml
appveyor.yml
tools/travis-ci/detect-avx2.c
tools/travis-ci/knownfailures-Ubuntu14.04-clang3.8.0-x86_64-Release-3rdP.txt
tools/travis-ci/run.sh

* Add a /arch:AVX2 config for AppVeyor
* It turns out that some workers used by Travis-CI and AppVeyor have AVX2 compatible CPUs, so when this is the case, run the tests.

Enable AVX2 at runtime on Travis-CI and AppVeyor

---

src/lib/openjp2/CMakeLists.txt

This enhances https://github.com/uclouvain/openjpeg/commit/5736b1a3683261a5b31fc19a691731dc9fce5920 to actually install the static libraries after they are built. Sorry for not this right in the original PR.

install static libraries

---

src/lib/openjp2/mqc.c
src/lib/openjp2/mqc.h
src/lib/openjp2/mqc_inl.h
src/lib/openjp2/t1.c
src/lib/openjp2/t1.h
src/lib/openjp2/tcd.c

This implements (on top of https://github.com/uclouvain/openjpeg/pull/786) checking of code stream errors when predictable termination is enabled. Warning are emitted when errors are found. To be honest,  I came with the numerical values used by those checks in a rather experimental way by running it on a set of good and corrupted images.
The relevant commit is https://github.com/uclouvain/openjpeg/pull/800/commits/c9f3d8865c4362d32047d11f5585af286f650cd4

Implement predictive termination check

---

src/bin/common/color.c
src/lib/openjp2/image.c
src/lib/openjp2/j2k.c
src/lib/openjp2/jp2.c
src/lib/openjp2/openjpeg.c
src/lib/openjp2/openjpeg.h
src/lib/openjp2/opj_common.h
src/lib/openjp2/t1.c
src/lib/openjp2/t1.h
src/lib/openjp2/t2.c
src/lib/openjp2/tcd.c
src/lib/openjp2/tcd.h

On MAPA_002.jp2, peak memory goes from 4.5 GB to 1.9 GB (including the 1.6 GB needed for the whole image)
The improvements consist of two main independant changes:
* the major one (4.5 GB->2.7 GB): in case of decoding of whole image consisting of a single time, use directly the tile component data as output image data. And save the use of the temporary buffer to transfer between both
* a more modest one (2.7->1.9GB) : avoid allocating memory to store the part of the codestream that is dedicated to a buffer. But instead point to the codestream buffer itself.
The major one has an annoying side effect: given that tile component data buffers are 16-byte aligned (for SSE code paths), we need in all code paths that alloc/free image->comps[].data to use aligned malloc/free as well (on Linux, …

Reduce memory decoding

---

src/bin/common/color.c
src/bin/jp2/convert.c
src/bin/jp2/convertbmp.c
src/bin/jp2/converttif.c
src/bin/jp2/opj_decompress.c
src/bin/jp2/opj_dump.c
src/lib/openjp2/j2k.c
src/lib/openjp2/j2k.h
src/lib/openjp2/jp2.c
src/lib/openjp2/jp2.h
src/lib/openjp2/openjpeg.h
src/lib/openjp2/tcd.h

@rouault ,
the minimal archive is attached.
winfried
[openjpeg-crashes-2017-07-30.zip](https://github.com/uclouvain/openjpeg/files/1187460/openjpeg-crashes-2017-07-30.zip)

Catch images broken by AFL

---

src/bin/jp2/converttif.c

Type mismatch in 'src/bin/jp2/converttif.c' found using PPC64.
winfried

Changes in converttif.c for PPC64

---

src/lib/openjp2/bench_dwt.c
src/lib/openjp2/dwt.c
src/lib/openjp2/dwt.h
src/lib/openjp2/j2k.c
src/lib/openjp2/opj_intmath.h
src/lib/openjp2/t1.c
src/lib/openjp2/t1.h
src/lib/openjp2/t2.c
src/lib/openjp2/t2.h
src/lib/openjp2/tcd.c
src/lib/openjp2/tcd.h
tests/CMakeLists.txt
tests/test_decode_area.c
tests/test_tile_encoder.c

Continuation of https://github.com/uclouvain/openjpeg/pull/990 (although in theory it could be applied independantly, but in practice stage2 only makes sense with stage1).
This lowers 'bin/opj_decompress -i ../MAPA.jp2 -o out.tif -d 0,0,256,256'  down to 0.860s (IDWT 5x3 case)
Note: for IDWT 5x3 the function that does subtile decoding doesn't use the recent SSE2/AVX2 optimizations

Subtile decoding: only apply IDWT on areas that participate to the window of interest

---

CMakeLists.txt
src/bin/jp2/opj_compress.c
src/lib/openjp2/CMakeLists.txt
src/lib/openjp2/bench_dwt.c
src/lib/openjp2/dwt.c
src/lib/openjp2/dwt.h
src/lib/openjp2/j2k.c
src/lib/openjp2/mct.c
src/lib/openjp2/mct.h
src/lib/openjp2/openjpeg.h
src/lib/openjp2/opj_includes.h
src/lib/openjp2/opj_intmath.h
src/lib/openjp2/sparse_array.c
src/lib/openjp2/sparse_array.h
src/lib/openjp2/t1.c
src/lib/openjp2/tcd.c
src/lib/openjp2/tcd.h
src/lib/openjp2/test_sparse_array.c
tests/CMakeLists.txt
tests/test_decode_area.c

The gist of this PR is commit https://github.com/uclouvain/openjpeg/commit/f9e9942330f476b66ac4a35d0ae521200878f343
```
Only allocate tile component buffer of the needed dimension instead of being the full tile size.
* Use a sparse array mechanism to store code-blocks and intermediate stages of
IDWT.
* IDWT, DC level shift and MCT stages are done just on that smaller array.
* Improve copy of tile component array to final image, by saving an intermediate
buffer.
* For full-tile decoding at reduced resolution, only allocate the tile buffer to
the reduced size, instead of the full-resolution size.
```
The effect is a reduction of the decoding time of "opj_decompress -i MAPA.jp2 -o out.tif -d 0,0,256,256" from 900ms to 190ms, and a reduction of RAM allocation from 2.27 GB to 265 MB (220 MB of …

Subtile decoding: memory use reduction and perf improvements

---

src/bin/jp2/opj_decompress.c
src/lib/openjp2/j2k.c
src/lib/openjp2/j2k.h
src/lib/openjp2/jp2.c
src/lib/openjp2/jp2.h
src/lib/openjp2/openjpeg.c
src/lib/openjp2/openjpeg.h
src/lib/openjp2/opj_codec.h
src/lib/openjp2/tcd.c
src/lib/openjp2/tcd.h
tests/nonregression/md5refs.txt
tests/nonregression/test_suite.ctest.in

#This adds a opj_set_decoded_components(opj_codec_t *p_codec,
OPJ_UINT32 numcomps, const OPJ_UINT32* comps_indices, OPJ_BOOL apply_color_transforms) function, and equivalent "opj_decompress -c compno[,compno]*" option.
When specified, neither the MCT transform nor JP2 channel transformations
will be applied (apply_color_transforms must be set to OPJ_FALSE)
Tests added for various combinations of whole image vs tiled-based decoding,
full or reduced resolution, use of decode area or not.

Add capability to decode only a subset of all components of an image.

---

src/bin/jpwl/convert.c

Add missing fclose() statement in error condition.

---

src/bin/jp2/convert.c

Coverity report:
CID 179466 (#1 of 1): Resource leak (RESOURCE_LEAK)
93. leaked_storage: Variable name going out of scope leaks the storage it points to.

Fix resource leak (CID 179466)

---

src/lib/openjp2/openjpeg.h

Edit docstring, I lost some hours on this because I'd assumed seek used `SEEK_CUR` behavior, and even had images loading once OPJ_DISABLE_TPSOT_FIX was defined.
A comment like this would have helped.

Note that seek uses SEEK_SET behavior.

---

src/bin/jp3d/convert.c

This replaces the unsafe sprintf() invocation by the safer snprintf()
one, with the correct buffer size to prevent buffer overflows.
This fixes #1085.

jp3d: Replace sprintf() by snprintf() in volumetobin()

---

src/bin/mj2/opj_mj2_extract.c

This renames the argument in the help output, as the latter better describes
the the purpose of this argument.

opj_mj2_extract: Rename output_location to output_prefix

---

src/bin/mj2/meta_out.c

This adds the appropriate variables to the invocation of fprintf(). They were
specified in the format string, but were missing in the actual call. This
fixes #1074 and #1075.

mj2: Add missing variable to format string in fprintf() invocation in meta_out.c

---

INSTALL.md

Building under msys/mingw doesn't automatically install the pkg config files needed to build GDAL and other libraries.

Add -DBUILD_PKGCONFIG_FILES to install instructions

---

src/lib/openjp2/j2k.c
src/lib/openjp2/jp2.c

Compiler warnings:
src/lib/openjp2/jp2.c:1008:35: warning:
too many arguments for format [-Wformat-extra-args]
src/lib/openjp2/j2k.c:1928:73: warning:
format ‘%d’ expects argument of type ‘int’, but argument 4 has type ‘OPJ_OFF_T {aka long int}’ [-Wformat=]

openjp2/jp2: Fix two format strings

---

cmake/OpenJPEGConfig.cmake.in

Hi,
Solaris usually installs cmake configure files to /usr/lib/cmake/<pkg>/ and /usr/lib/$(MACH64)/cmake/<pkg>/ directories, however, file OpenJPEGConfig.cmake.in assumes the fixed relative path that can be wrong if OPENJPEG_INSTALL_PACKAGE_DIR variable is manually changed.
The proposed change, tested on Solaris, Linux, and Windows, solves this problem by replacing the fixed relative path with the real one.

Relative path to header files is hardcoded in OpenJPEGConfig.cmake.in file

---

src/bin/jp2/opj_decompress.c
src/bin/mj2/opj_mj2_compress.c
src/lib/openjp2/dwt.c
src/lib/openjp2/openjpeg.h
src/lib/openmj2/mj2.c
src/lib/openmj2/tcd.h
thirdparty/README.txt

All typos were found by Codespell.

Fix some typos in code comments and documentation

---

src/lib/openjpip/sock_manager.c

ssize_t is a POSIX type which is declared in POSIX include files.
Mingw-w64 provides it also for Windows.
Use the local declaration only with MS compilers.

Use local type declaration for POSIX standard type only for MS compiler

---

src/lib/openjp2/opj_intmath.h

I'm not sure if this will address https://github.com/uclouvain/openjpeg/issues/231 or not, but while looking I noticed that the int_ceildiv has this casting applied, so it would make sense the uint_ceildiv would as well, but I'm not super proficient in C.
If this won't work, please close this PR with extreme prejudice :)

Cast on uint ceildiv

---

src/bin/jp2/convertbmp.c

```
In the case where a BMP file declares compression 3 (BI_BITFIELDS) with header size <= 56, all bitmask values keep their initialization value 0. This may lead to various undefined behavior later e.g. when doing 1 << (l_comp->prec - 1).
This issue does not affect files with bit count 16 because of a check added in 16240e2 which sets default values to the color masks if they are all 0.
This patch adds similar checks for the 32 bit case.
Also, if a BMP file declares compression 3 with header size >= 56 and intentional 0 bitmasks, the same issue will be triggered in both the 16 and 32 bit count case.
This patch adds checks to bmp_read_info_header() rejecting BMP files with "intentional" 0 bitmasks. These checks might be removed in the future when proper handling of zero bitmasks will be …
```

CVE-2018-5785: fix issues with zero bitmasks

---

src/bin/jp2/convertbmp.c
src/bin/jp2/converttif.c
src/bin/jp2/opj_compress.c
src/bin/jp2/opj_decompress.c
src/lib/openjp2/jp2.c
src/lib/openjp2/t1.c
src/lib/openmj2/j2k.c
src/lib/openmj2/jp2.c

Put sizeof to the beginning of the multiplication to enforce that
size_t instead of smaller integer types is used for the calculation.
This fixes warnings from LGTM:
Multiplication result may overflow 'unsigned int'
before it is converted to 'unsigned long'.
It also allows removing some type casts.

Fix some potential overflow issues

---

src/lib/openjp3d/tcd.c

When compressing a lot of slices (starting from 44 FullHD slices with 3 8bit components in our experiments) the rate values are high enough to cause an int overflow that leads to negative lengths and wrong results. The cast happens too late.
Fixes #1162

Int overflow fixed

---

src/bin/jp2/convert.c
src/bin/jp3d/convert.c
src/bin/jpwl/convert.c

Missing buffer length formatter in fscanf call might lead to write stack buffer overflow.
(same patch as  e5285319229a5d77bf316bb0d3a6cbd3cb8666d9)
Fixes #1044 (CVE-2017-17480).

jp3d/jpwl convert: fix write stack buffer overflow

---

src/bin/jp2/convertbmp.c

width/length dimensions read from bmp headers are not necessarily valid. For instance they may have been maliciously set to very large values with the intention to cause DoS (large memory allocation, stack overflow). In these cases we want to detect the invalid size as early as possible.
This PR introduces a counter which verifies that the number of written bytes corresponds to the advertised width/length.
If advertised size and actual size don't match, we return false which basically aborts execution.
We might alternatively consider resizing the data array and continue the execution normally. Do you think this would be preferable ?
This PR fixes #1059.

convertbmp: detect invalid file dimensions early (CVE-2018-6616)

---

src/lib/openjp2/t1.c

Fixes #1053 / CVE-2018-5727
Note: I don't consider this issue to be a security vulnerability, in
practice.
At least with gcc or clang compilers on x86_64 which generate the same
assembly code with or without that fix.

opj_t1_encode_cblks: fix UBSAN signed integer overflow

---

src/bin/jp2/opj_decompress.c
src/lib/openjp2/j2k.c

Previously the caller had to check whether each component data had
been decoded. This means duplicating the checking in every user of
openjpeg which is unnecessary. If the caller wantes to decode all
or a set of, or a specific component then openjpeg ought to error
out if it was unable to do so.
Fixes #1158.

openjp2/j2k: Report error if all wanted components are not decoded.

---

tools/travis-ci/abi-check.sh

There is currently a false positive ABI check failure between v2.3.1
and current. It disappears when removing the generated reports of v2.3.1
and recreating them. It is likely that some tooling has evolved since
the initial v2.3.1 report generation.

abi-check.sh: fix false postive ABI error, and display output error log

---

src/lib/openjp2/pi.c
src/lib/openjp2/pi.h

Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=18979

pi.c: avoid integer overflow, resulting in later invalid access to memory in opj_t2_decode_packets()

---

tests/fuzzers/GNUmakefile
tests/fuzzers/build_google_oss_fuzzers.sh

This was changed some time ago (https://google.github.io/oss-fuzz/getting-started/new-project-guide/) but the build didn't fail as there is a fallback mechanism. The main advantage of the new approach is that for libFuzzer this produces more performant binaries (as `$LIB_FUZZING_ENGINE` expands into `-fsanitize=fuzzer`, which links libFuzzer from the compiler-rt, allowing better optimization tricks).
I'm also experimenting with dataflow (https://github.com/google/oss-fuzz/issues/1632) on your project, and the dataflow config doesn't have a fallback (as it's a new configuration), therefore I'm proposing a change to migrate from `-lFuzzingEngine` to `$LIB_FUZZING_ENGINE`.

tests/fuzzers: link fuzz binaries using $LIB_FUZZING_ENGINE.

---

src/lib/openjp2/tcd.c

That could lead to later assertion failures.
Fixes #1231 / CVE-2020-8112

opj_tcd_init_tile(): avoid integer overflow

---

tests/nonregression/checkmd5refs.cmake
tests/nonregression/md5refs.txt
tests/nonregression/test_suite.ctest.in

Fixes #1233
libtiff 4.1 slightly modifies the way it generates files. So
add the new expected md5sum.
Not super elegant solution admitedly.

tests: add alternate checksums for libtiff 4.1

---

src/bin/jp2/convert.c
src/bin/jp2/convertpng.c
src/bin/jp2/converttif.c

Prevent crashes like:
opj_decompress -i 0722_5-1_2019.jp2 -o out.ppm -r 4 -t 0
where 0722_5-1_2019.jp2 is
https://drive.google.com/file/d/1ZxOUZg2-FKjYwa257VFLMpTXRWxEoP0a/view?usp=sharing

opj_decompress: add sanity checks to avoid segfault in case of decoding error

---

src/bin/jp3d/convert.c
src/bin/jpip/opj_jpip_transcode.c
src/bin/jpwl/convert.c
src/bin/jpwl/opj_jpwl_compress.c
src/bin/jpwl/opj_jpwl_decompress.c
src/bin/mj2/mj2_to_metadata.c
src/bin/mj2/opj_mj2_compress.c
src/bin/mj2/opj_mj2_decompress.c
src/lib/openjp3d/t2.c
src/lib/openjpip/auxtrans_manager.c
src/lib/openjpip/box_manager.c
src/lib/openjpip/index_manager.c
src/lib/openjpip/jp2k_decoder.c
src/lib/openjpip/openjpip.c
src/lib/openmj2/mj2.c
src/lib/openmj2/mj2_convert.c

This issues were found by cppcheck and coverity.

Fix resource leaks

---

src/bin/jp2/opj_compress.c
src/lib/openjp2/j2k.c
src/lib/openjp2/j2k.h
src/lib/openjp2/jp2.c
src/lib/openjp2/jp2.h
src/lib/openjp2/openjpeg.c
src/lib/openjp2/openjpeg.h
src/lib/openjp2/opj_codec.h
src/lib/openjp2/pi.c
src/lib/openjp2/pi.h
src/lib/openjp2/t2.c
src/lib/openjp2/t2.h
src/lib/openjp2/tcd.c
src/lib/openjp2/tcd.h
tests/nonregression/test_suite.ctest.in

* -PLT switch added to opj_compress
* Add a opj_encoder_set_extra_options() function that
accepts a PLT=YES option, and could be expanded later
for other uses.
-------
Testing with a Sentinel2 10m band, T36JTT_20160914T074612_B02.jp2,
coming from S2A_MSIL1C_20160914T074612_N0204_R135_T36JTT_20160914T081456.SAFE
Decompress it to TIFF:
```
opj_decompress -i T36JTT_20160914T074612_B02.jp2 -o T36JTT_20160914T074612_B02.tif
```
Recompress it with similar parameters as original:
```
opj_compress -n 5 -c [256,256],[256,256],[256,256],[256,256],[256,256] -t 1024,1024 -PLT -i T36JTT_20160914T074612_B02.tif -o T36JTT_20160914T074612_B02_PLT.jp2
```
Dump codestream detail with GDAL dump_jp2.py utility (https://github.com/OSGeo/gdal/blob/master/gdal/swig/python/samples/dump_jp2.py)
```
python …
```

Add support for generation of PLT markers in encoder

---

src/lib/openjp2/j2k.c
tests/nonregression/CMakeLists.txt

This is my attempt to fix issue #1210 
Merging this commit may need changes in `openjpeg-data` as well for the test files since three files now fail consistently, but the `baseline` directory in `openjpeg-data` contains fully parsed header information.
If you prefer I could change the code to only warn in these circumstances (and update the test cases accordingly), but it that would a step away from the specification. Let me know what you think.

Add check to validate SGcod/SPcoc/SPcod parameter values.

---

src/lib/openjp2/t1.c

Previously when the handle failed to be created (e.g. when
opj_calloc returned NULL due to low memory), the code still
assumed that the t1 handle pointer was valid and dereferenced
NULL, causing a crash. After this commit OpenJPEG will instead
error out under this condition.
This fixes issue #1255.

openjp2: Error out if failing to create Tier 1 handle.

---

src/lib/openjp2/t1.c

Previously the Tier 1 handle was not freed when setting it as TLS failed.
This fixes issue #1257.

openjp2: Plug memory leak when setting data as TLS fails.

---

src/lib/openjp2/j2k.c

openjp2: Plug image leak when failing to allocate codestream index.

---

src/bin/jp2/opj_decompress.c

Fixes #1261
Credits to @Ruia-ruia for reporting and analysis.

opj_decompress: fix double-free on input directory with mix of valid and invalid images

---

src/lib/openjp2/tcd.c

This PR avoids heap-buffer-overflow in `-M 4 -IMF 2K`.

Encoder: grow again buffer size

---

src/lib/openjp2/tcd.c

It has a memory leak when using opj_compress with `-PLT`.
```
➜  ~ /openjpeg/build/bin/opj_compress -i ./sample.png  -o ./a.j2c  -PLT
[INFO] tile number 1 / 1
[INFO] Generated outfile ./a.j2c
encode time: 2 ms 
=================================================================
==25432==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 16 byte(s) in 1 object(s) allocated from:
#0 0x7fb179289d28 in __interceptor_calloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xded28)
#1 0x7fb178f807d9 in opj_tcd_marker_info_create /home/yuan/openjpeg/src/lib/openjp2/tcd.c:2837
SUMMARY: AddressSanitizer: 16 byte(s) leaked in 1 allocation(s).
```
It has to free marker_info in opj_j2k_write_sod in lib/openjp2/j2k.c before return.

Free p_tcd_marker_info to avoid memory leak

---

cmake/OpenJPEGConfig.cmake.in

This fixes the case where the cmake file is accessed via a symlink.
I'm not sure I understand the original code and why all the complexity is needed. If we do need all that, then we may need to canonicalize SELF_DIR.

Use INC_DIR for OPENJPEG_INCLUDE_DIRS (fixes uclouvain#1174)

---

thirdparty/include/zlib.h
thirdparty/libz/zlib.h

There is a small typo in thirdparty/include/zlib.h, thirdparty/libz/zlib.h.
Should read `produced` rather than `producted`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: fix simple typo, producted -> produced

---

doc/CMakeLists.txt

Use `${OPENJPEG_INSTALL_DOC_DIR}` as `DESTINATION` of HTML documents, instead of `share/doc`.

Set ${OPENJPEG_INSTALL_DOC_DIR} to DESTINATION of HTMLs

---

CMakeLists.txt
thirdparty/CMakeLists.txt

By default, CMake assumes that the project is using both C and C++.  By
explicitly passing 'C' as argument of the project() macro, we tell CMake
that only C is used, which prevents CMake from erroring out if a C++
compiler doesn't exist.
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>
[Retrieved (and slightly updated by adding enable_language(CXX) if
WITH_ASTYLE is set) from:
https://git.buildroot.net/buildroot/tree/package/openjpeg/0003-CMakeLists.txt-Don-t-require-a-C-compiler.patch]
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

CMakeLists.txt: Don't require a C++ compiler

---

thirdparty/CMakeLists.txt

thirdparty: lcms2: append flags found by pkg-config if available
This change allows to get all required CFLAGS/LDFLAGS in case of static only
build.
Fixes a buildroot build failure (see [1], [2] and [3]).
[1] http://autobuild.buildroot.net/results/5ce/5cee20afd8bef5268832cddcb3a5270746be7a57
[2] http://lists.busybox.net/pipermail/buildroot/2016-November/177187.html
[3] http://lists.busybox.net/pipermail/buildroot/2016-November/177188.html
Signed-off-by: Peter Seiderer <ps.report@gmx.net>
---
Depends on https://github.com/uclouvain/openjpeg/pull/866

Fix lcms2 static linking using pgk config

---

CMakeLists.txt

Hi, 
I think this test should not run on the emscripten platform because of :
https://github.com/emscripten-core/emscripten/blob/dff33368427fba16745c8ce52f11484a67b2855d/cmake/Modules/TestBigEndian.cmake#L5
changing CMAKE_ROOT to point to `..,/emsdk/upstream/emscripten/cmake` does not solve the issue, as there are some .cmake files that are needed and are not on emsdk.

emscripten: disable big endian test

---

CMakeLists.txt

thank you to  @ePirat for finding the issue, it turns out that !EMSCRIPTEN does not evaluate to 1 on other platforms, so the the #1345 actually disabled the test for all platforms.
sorry about the churn

fix #1345: don't remove big endian test for other platforms

---

src/lib/openjp2/j2k.c

These issue were found when the code was analyzed by Coverity.

opj_j2k_is_imf_compliant: Fix argument formatting for warnings.

---

src/lib/openjp2/j2k.c

This was discovered when scanning the code using Coverity.

opj_j2k_is_imf_compliant: Fix out of bounds access

---

src/bin/jp2/opj_decompress.c

Fixes #1368：exist a issues of freeing uninitialized pointer in src/bin/jp2/opj_decompress.c，that will cause a segfault
Initialize the newly allocated memory

fix issues 1368: exist a issues of freeing uninitialized pointer in src/bin/jp2/opj_decompress.c，that will cause a segfault

---

src/lib/openjp2/pi.c

LGTM warning: Comparison result is always the same

---

src/lib/openjp2/dwt.c
src/lib/openjp2/opj_intmath.h

Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=11700 and https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=30646

Avoid integer overflows in DWT. 

---

CMakeLists.txt
src/bin/jp2/convertpng.c
src/bin/jp2/opj_decompress.c
src/bin/jp2/windirent.h
src/bin/jpip/README
src/bin/jpip/opj_jpip_addxml.c
src/bin/wx/OPJViewer/source/OPJViewer.cpp
src/lib/openjp2/bench_dwt.c
src/lib/openjp2/cio.h
src/lib/openjp2/dwt.c
src/lib/openjp2/ht_dec.c
src/lib/openjp2/j2k.c
src/lib/openjp2/jp2.c
src/lib/openjp2/openjpeg.h
src/lib/openjp2/opj_intmath.h
src/lib/openjp2/pi.c
src/lib/openjp2/t1.h
src/lib/openjp2/t1_ht_generate_luts.c
src/lib/openjp2/t2.c
src/lib/openjpip/auxtrans_manager.c
src/lib/openjpip/imgsock_manager.h
src/lib/openjpip/index_manager.c
src/lib/openjpip/jpip_parser.c
src/lib/openjpip/metadata_manager.h
src/lib/openjpip/mhixbox_manager.h
thirdparty/README.txt

Fix some typos (found by codespell)

---

.vscode/settings.json
src/bin/jp2/opj_compress.c
src/bin/jp2/opj_decompress.c
src/bin/jp2/opj_dump.c

Added a multiplication check before the call to calloc, see my comment on 79c7d7a

Added overflow check for CVE-2021-29338 

---

.vscode/settings.json
src/bin/jp2/opj_compress.c
src/bin/jp2/opj_decompress.c
src/bin/jp2/opj_dump.c

As discussed in pull request 1396, added a check for integer overflow. 
Change list:
Defined num_images as unsigned int
Moved the if statement to check for an empty directory to the beginning of the read directory section
Added a check to see if num images rolls back to zero when incrementing.

Added check for integer overflow in get_num_images 

---

src/bin/jp2/opj_compress.c
src/lib/openjp2/j2k.c
src/lib/openjp2/j2k.h
src/lib/openjp2/openjpeg.h

and add a -GuardBits option to opj_compress.
The recently-released SMPTE DCP Bv2.1 Application Profile (link below)
says that the number of guard bits in the QCD marker shall be 1 for 2K
content and 2 for 4K content. This change allows the number of guard bits
to be configured, so that users of openjpeg have the control they need to meet the specification.
https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=9161348
This is an alternative implementation of https://github.com/uclouvain/openjpeg/pull/1388
that keeps ABI unchanged.

opj_encoder_set_extra_options(): add a GUARD_BITS=value option

---

src/bin/jp2/opj_decompress.c
src/lib/openjp2/j2k.c
src/lib/openjp2/j2k.h
src/lib/openjp2/jp2.c
src/lib/openjp2/jp2.h
src/lib/openjp2/openjpeg.c
src/lib/openjp2/openjpeg.h
src/lib/openjp2/opj_codec.h
src/lib/openjp2/t2.c

This is an updated version of #1251 by @chafey

Updated "added support for partial bitstream decoding"

---

.github/workflows/cifuzz.yml

Add CIFuzz Github action to build and run fuzzers on pull requests.
This will run the fuzzers for 600 seconds (split between all the fuzzers) in the CI when a pull request is made and is a service by OSS-fuzz. It can help with catching bugs early and catch regressions.
Documentation for CIFuzz can be found here: https://google.github.io/oss-fuzz/getting-started/continuous-integration/
Signed-off-by: David Korczynski <david@adalogics.com>

CI: Add CIFuzz action

---

tests/fuzzers/opj_decompress_fuzzer_J2K.cpp
tests/fuzzers/opj_decompress_fuzzer_JP2.cpp

As I checked locally, separating fuzz targets for J2K and JP2 leads to increased coverage.
I came across this case while testing our new tool [Fuzz-Introspector](https://github.com/ossf/fuzz-introspector) on OSS-Fuzz projects.

Separate fuzz targets to increase coverage

---

src/lib/openjp2/libopenjp2.pc.cmake.in
src/lib/openjpip/libopenjpip.pc.cmake.in

allows for the usage of $(pkgconf --static --cflags libopenjp2) to produce
the proper CFLAGS for static linking. Relies on pkgconf rather than pkg-config.

pkgconfig: Define OPJ_STATIC for static linking with pkgconf

---

src/lib/openjp2/ht_dec.c

Fix windows arm builds

---

src/lib/openjp2/ht_dec.c

Fix opj_t1_allocate_buffers malloc size error

---

thirdparty/CMakeLists.txt

Note that the fix might be partial only for static-only builds (cf
comments)
Ammends PR #866 and #867
CC @ffontaine / @pseiderer

Build: fix linking of executables on some systems where TIFF/LCMS2 static libraries are not in system directories (fixes #1430)

---

CMakeLists.txt
cmake/OpenJPEGConfig.cmake.in

Using CMakePackageConfigHelpers, we can generate a relocatable
OpenJPEGConfig.config, using the PATH_VARS feature to make
CMAKE_INSTALL_LIBDIR relative to the installed location.
This change is needed for me when cross-compiling since
CMAKE_INSTALL_FULL_LIBDIR is a path inside the sysroot rather than
an absolute path to the actual includes. Without this change poppler
ends up passing a -I flag that does not exist.
This includes fallback code for CMake 2.8, which adds a bit of complexity,
since I'm not sure if raising the minimum to 3.0 (now over 8 years old)
is acceptable.

Make OpenJPEGConfig.cmake relocatable with CMake > 3.0

---

src/lib/openjp2/ht_dec.c

Hi Even, Everyone,
This is to address the issue with the Fuzzer in
https://bugs.chromium.org/p/chromium/issues/detail?id=1343737
A wrong sequence should produce erroneous result, but should not cause a crash.
A similar if statement can be added to mel_read(), but this requires more changes -- no fuzzing issue produced for this.
I tried to run openjpeg fuzzing, but I did not know how to tell oss-fuzz what source to use.  I tried
```python infra/helper.py build_fuzzers --architecture x86_64 --sanitizer address openjpeg ~/openjpeg```
The first time, it ran with an error message at the end about conformance.
The second time, it is producing an error ```mkdir: cannot create directory 'build': File exists```, but I do not know where this folder is to delete it.
I am happy to run fuzzing on this …

Replace the assert in mel_init to an if statement to address an issue with fuzzing.

---

src/bin/jp2/opj_compress.c
src/lib/openjp2/bio.c
src/lib/openjp2/bio.h
src/lib/openjp2/j2k.c
src/lib/openjp2/j2k.h
src/lib/openjp2/openjpeg.h
src/lib/openjp2/t1.c
src/lib/openjp2/t2.c
src/lib/openjp2/tcd.c
src/lib/openjp2/tcd.h
src/lib/openjp2/tgt.c

- Avoid doing 128 iterations all the time, and stop when the threshold
doesn't vary much
- Avoid calling costly opj_t2_encode_packets() repeatdly when bisecting the
layer ratio if the truncation points haven't changed since the last
iteration.
When used with the GDAL gdal_translate application to convert a 11977 x
8745 raster with data type UInt16 and 8 channels, the conversion time
to JPEG2000 with 20 quality layers using disto/rate allocation (
-co "IC=C8" -co "JPEG2000_DRIVER=JP2OPENJPEG" -co "PROFILE=NPJE_NUMERICALLY_LOSSLESS"
creation options of the GDAL NITF driver) goes from 5m56 wall clock
(8m20s total, 12 vCPUs) down to 1m16 wall clock (3m45 total).
to be compared to 34s wall clock (3m5 total) for single quality layer output.

Significant speed-up rate allocation by rate/distoratio ratio

---

src/lib/openjp2/jp2.c

The issue was found while fuzzing opencv:
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=47342
The read overflow triggered by reading `src[j]` in
```cpp
for (j = 0; j < max; ++j) {
dst[j] = src[j];
}
```
The max is calculated as `new_comps[pcol].w * new_comps[pcol].h`, however the `src = old_comps[cmp].data;` which may have different `w` and `h` dimensions.

Fix Heap-buffer-overflow READ in opj_jp2_apply_pclr

---

appveyor.yml
src/lib/openjp2/j2k.c

This makes it possible to build j2k.c without warnings using the macOS 13 SDK. Calls to `sprintf` are replaced with `snprintf`, passing appropriate buffer sizes.
It doesn’t appear that any of the changed uses of `sprintf` were actually unsafe, so no behavior change is expected aside from SDK compatibility.
The macOS 13 SDK deprecates `sprintf` as it’s difficult to use safely. The deprecation warning message is visible when building C++, but it is not normally visible when building plain C code due to a quirk in how `sprintf` is declared in the SDK. However, the deprecation message is visible when building plain C under Address Sanitizer (`-fsanitize=address`). This discrepancy was discovered at https://crbug.com/1381706 and reported to Apple with a copy at …

openjp2/j2k: replace sprintf calls with snprintf

---

CMakeLists.txt
src/bin/jp2/opj_compress.c
src/bin/jp2/opj_decompress.c
src/lib/openjp2/ht_dec.c
src/lib/openjp2/j2k.c
src/lib/openjp2/openjpeg.c
src/lib/openjp2/thread.c

And fix strict-prototypes/missing-prototypes warnings.

CMake: error out on warnings for strict/missing prototypes.

---

src/lib/openjp2/ht_dec.c

Hi! We've been fuzzing openjpeg with [sydr-fuzz](https://github.com/ispras/oss-sydr-fuzz) security predicates and we found incorrect using of `memcpy` in `ht_dec.c:1215`.
In function opj_t1_ht_decode_cblk at line 1215  there is a `memcpy` call: `memcpy(cblkdata + cblk_len, cblk->chunks[i].data, cblk->chunks[i].len)`. We have found input where `cblk_len` is NULL, so therefore nullptr + offset is put in destination parameter of `memcpy` and that is incorrect. Also, if `cblk_len` is NULL and cblk->chunks[i].len is not zero, that instantly leads to crash. 
- OS: ubuntu 20.04
- commit: 6af39314bdb43cb9c7adcdbc7aa9381af42b52ba
1. Build [docker container](https://github.com/ispras/oss-sydr-fuzz/tree/master/projects/openjpeg):
```
sudo docker build -t oss-sydr-fuzz-openjpeg .
```
2. Run docker …

fix ht_dec.c:1215

---

src/lib/openjp2/j2k.c

Hi! We've been fuzzing openjpeg with [sydr-fuzz](https://github.com/ispras/oss-sydr-fuzz) security predicates and we found integer overflow error in `j2k.c:3962`.
In function opj_j2k_merge_ppm at line 3962 integer overflow occurs in variable `l_ppm_data_size` (the value of `l_N_ppm` was 4294967295). Also there is a comment that says it can't overflow, but `l_N_ppm`  (returned from `opj_read_bytes`) turned out to be too big. So I've just added a checked for that overflow, but maybe it is also possible to check for its validity in `opj_read_byte`.
- OS: ubuntu 20.04
- commit: 6af39314bdb43cb9c7adcdbc7aa9381af42b52ba
1. Build [docker container](https://github.com/ispras/oss-sydr-fuzz/tree/master/projects/openjpeg):
```
sudo docker build -t oss-sydr-fuzz-openjpeg .
```
2. Run docker …

Integer Overflow at j2k.c:3962

---

src/lib/openjp2/tcd.c

(likely harmless issue as we don't dereference it)

opj_tcd_dc_level_shift_decode(): avoid increment nullptr (fixes #1480)

---

src/lib/openjp2/ht_dec.c

Use NEON instructions for ARM64 (implementation based on microsoft/STL#2127).
Godbolt output here: https://godbolt.org/z/q7GPTqT14

ht_dec.c: Improve MSVC arm64 popcount performance

---

src/lib/openjp2/openjpeg.c

Fix for a compilation error with `MSVC/14.37.32822/bin/HostX64/x64/cl.exe`:
```
openjpeg\src\lib\openjp2\openjpeg.c(438): error C2491: 'opj_decoder_set_strict_mode': definition of dllimport function not allowed
```

Fix compiler error on Windows

---

CMakeLists.txt
src/bin/jp2/CMakeLists.txt
src/lib/openjp2/CMakeLists.txt
src/lib/openjpip/CMakeLists.txt
tests/nonregression/CMakeLists.txt
tools/ctest_scripts/travis-ci.cmake

Compatibility for cmake version < 3.5 is now deprecated in cmake and specifying version below 3.5 in cmake_minimum_required produces a warning.[1]
[1] https://cmake.org/cmake/help/latest/release/3.27.html#deprecated-and-removed-features

CMake: drop support for cmake < 3.5

---

CMakeLists.txt

Add the missing cmake version file, so that software using the library can check for version compatibility.

Add cmake version file

---

src/bin/common/color.c

Now Valgrind output is clean:
```
$ valgrind ./bin/opj_decompress -i ./poc.j2k -o out.png
==167167== Memcheck, a memory error detector
==167167== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==167167== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==167167== Command: ./bin/opj_decompress -i ./poc.j2k -o out.png
==167167== 
[INFO] Start to read j2k main header (0).
[ERROR] Unknown progression order in COD marker
[WARNING] Unknown marker
[ERROR] Unknown progression order in COD marker
[WARNING] Unknown marker
[WARNING] Unknown marker
[WARNING] Unknown marker
[ERROR] Unknown progression order in COD marker
[WARNING] Unknown marker
[WARNING] Unknown marker
[WARNING] Unknown marker
[INFO] Main header has been correctly decoded.
[INFO] No decoded area …
```

opj_decompress: fix off-by-one read heap-buffer-overflow in sycc420_to_rgb() when x0 and y0 are odd (CVE-2021-3575, fixes #1347)

---

src/lib/openjp2/t2.c

(alternate fix to https://github.com/uclouvain/openjpeg/pull/1488)

opj_t2_read_packet_header(): avoid unsigned integer overflow

---

src/lib/openjp2/openjpeg.h
src/lib/openjp2/opj_config.h.cmake.in

It was previously included by openjpeg.h

openjpeg.h: make sure to include opj_config.h (fixes #1514)

---

src/bin/jp2/convert.c

There is a swap16() function which conflicts with such a macro
in the endian.h header.  uint16_t swap16(uint16_t val16);

Fix building on OpenBSD big endian hosts

---

.github/workflows/cifuzz.yml

https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/
> With the introduction of v4, we will be deprecating v1 and v2 of actions/upload-artifact, actions/download-artifact, and related npm packages on June 30, 2024. We strongly encourage customers to update their workflows to begin using v4 of the artifact actions.

Updated actions/upload-artifact to v4

---

src/lib/openjp2/j2k.c

Hi! I've been fuzzing openjpeg with [sydr-fuzz](https://github.com/ispras/oss-sydr-fuzz) security predicates and I found integer overflow error in `j2k.c:9614`.
In function `opj_j2k_read_tile_header` at line 9614 integer overflow occurs when value `l_marker_size + 2` is subtracted from variable `p_j2k->m_specific_param.m_decoder.m_sot_length` and value from this variable is less than `l_marker_size + 2`. So here i decided just to add a checker for valid data.
- OS: ubuntu 20.04
- commit: 70e6263705334f854a27340e34ede11a767918ed
1. Build [docker container](https://github.com/ispras/oss-sydr-fuzz/tree/master/projects/openjpeg):
```
sudo docker build -t oss-sydr-fuzz-openjpeg .
```
2. Run docker container:
```
sudo docker run --privileged --network host -v /etc/localtime:/etc/localtime:ro …
```

Integer Overflow at j2k.c:9614

---

CHANGELOG.md

I realise these typos are actually in the issue titles, but I thought it might still be helpful to allow people to more clearly understand what the CHANGELOG is referring to.

Fixed typos

---

.github/workflows/build.yml
src/lib/openjp2/j2k.c

Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=68763

opj_j2k_decode_tiles(): avoid use of uninitialized l_current_tile_no variable

---

src/lib/openjp2/jp2.c

As per
https://github.com/uclouvain/openjpeg/blob/70e6263705334f854a27340e34ede11a767918ed/src/lib/openjp2/jp2.c#L2874-L2884
adds CMYK and EYCC to
https://github.com/uclouvain/openjpeg/blob/70e6263705334f854a27340e34ede11a767918ed/src/lib/openjp2/jp2.c#L1992-L1998

Support setting enumcs for CMYK and EYCC color space

---

src/lib/openjp2/t1.c
src/lib/openjp2/t2.c
src/lib/openjp2/tcd.h

Avoid heap-buffer-overflow read on corrupted image in non-strict mode

---

src/lib/openjp2/t2.c
tests/nonregression/test_suite.ctest.in

reference from Rec. ITU-T T.800 (06/2019):
- Table A.13 – Coding style parameter values for the Scod parameter
- Section A.8.1 Start of packet (SOP)
- Section A.8.2 End of packet header (EPH)
mitigates #1472 (this just mitigates the exact PoC provided in #1472 but clearing the EPH presence from csty allows to see the behavior mentioned in #1472 again)
requires  https://github.com/uclouvain/openjpeg-data/pull/25

fix: when EPH markers are specified, they are required.

---

src/lib/openjp2/dwt.c
src/lib/openjp2/t1.c

Encoder: performance gain ~0.1%​
Decoder: performance gain ~2.5%

Add AVX2 and AVX512 optimization

---

src/lib/openjp2/j2k.c

The fix of 2c0823cb30a70319c704565b59f496e490a3c7f9 (#1530) broke decoding of some JPEG2000 files where Isot==0, Psot==0, TPsot==0 and TNsot==0 like the following ones from the GDAL autotest suite: autotest/gdrivers/data/jpeg2000/stefan_full_rgba_alpha_1bit.jp2 autotest/gdrivers/data/jpeg2000/3_13bit_and_1bit.jp2

Amend fix of PR 1530 regarding m_sot_length check

---

src/lib/openjp2/j2k.c
src/lib/openjp2/openjpeg.h

make opj_decoder_set_strict_mode(, true) to disable it too
Adresses the use case of https://lists.osgeo.org/pipermail/gdal-dev/2024-November/059805.html where Sentinel2 L1C JPEG2000 files are made of a single tile-part per tile.
Ammends https://github.com/uclouvain/openjpeg/pull/514

Do not turn on 'TPsot==TNsot detection fix' when TNsot==1, and 

---

src/lib/openjp2/j2k.c

opj_j2k_add_tlmarker(): validate that current tile-part number if smaller that total number of tile-parts

---

src/bin/common/color.c

Fixes #1563
Also adjusts sycc420_to_rgb() for potential similar issue (amending commit 7bd884f8750892de4f50bf4642fcfbe7011c6bdf)

sycc422_to_rgb(): fix out-of-bounds read accesses when 2 * width_component_1_or_2 + 1 == with_component_0

---

src/lib/openjp2/jp2.c

Consider the case where the caller has not set the p_image pointer to NULL before calling opj_read_header().
If opj_j2k_read_header_procedure() fails while obtaining the rest of the marker segment when calling opj_stream_read_data() because the data stream is too short, then opj_j2k_read_header() will never have the chance to initialize p_image, leaving it uninitialized.
opj_jp2_read_header() will check the p_image value whether opj_j2k_read_header() suceeded or failed. This may be detected as an error in valgrind or ASAN.
The fix is to check whether opj_j2k_read_header() suceeded before using the output argument p_image.

opj_jp2_read_header: Check for error after parsing header.

---

src/lib/openjp2/jp2.c

When I set a color profile in write I always get an assert in `opj_jp2_write_colr()` (line 831). I've been using the library for a short time, but I didn't find any other way to pass the profile on write. Looking at the code it seems that the color profile set in the image is never copied to `jp2->color`.

Fixed ICC profile copy failure on write

---

CMakeLists.txt

Fix CMake warning: Compatibility with CMake < 3.10 will be removed
