uclouvain/openjpeg

src/lib/openjp2/tcd.c

Prevent overflow when coding 16 bits images

---

src/lib/openjp2/j2k.c
src/lib/openjp2/jp2.c
src/lib/openjp2/jp2.h

Add some missing static keywords

---

src/lib/openjp2/opj_includes.h
src/lib/openjp2/opj_intmath.h

Use __emul under msvc x86 for fast 64 = 32 * 32

---

CMakeLists.txt
src/lib/openjp2/CMakeLists.txt
src/lib/openjp3d/CMakeLists.txt
src/lib/openjpip/CMakeLists.txt
src/lib/openjpwl/CMakeLists.txt
src/lib/openmj2/CMakeLists.txt

issue #488
See also
http://public.kitware.com/pipermail/cmake/2015-April/060479.html

better -ffast-math handling

---

src/lib/openjp2/event.h
src/lib/openjp2/function_list.c
src/lib/openjp2/function_list.h
src/lib/openjp2/image.c
src/lib/openjp2/j2k.c
src/lib/openjp2/jp2.c
src/lib/openjp2/openjpeg.c
src/lib/openjp2/opj_includes.h
src/lib/openjp2/t2.c
src/lib/openjp2/t2.h
src/lib/openjp2/tcd.c
src/lib/openjp2/tcd.h
src/lib/openjp2/tgt.c
src/lib/openjp2/tgt.h

Remove printf/fprintf to stdout/stderr throughout openjp2 lib

---

src/lib/openjp2/j2k.c

Add check for seek support before trying TPsot==TNsot workaround

---

appveyor.yml
src/lib/openjp2/jp2.c
tests/nonregression/md5refs.txt
tests/nonregression/test_suite.ctest.in
tools/travis-ci/run.sh

Fix undefined size jp2 box handling

---

src/lib/openjp2/opj_malloc.c

Fix grammar in comment

---

src/lib/openjp2/t1_generate_luts.c

Also reorder initialization to follow declaration order

Fix uninitialized variable reported by cppcheck

---

src/lib/openjp2/opj_includes.h

Do not define __attribute__ in opj_includes.h

---

src/lib/openmj2/opj_malloc.h

Remove whitespace and CR at line endings

---

tests/nonregression/md5refs.txt
tests/nonregression/test_suite.ctest.in

Add test for PR 818

---

tests/nonregression/test_suite.ctest.in

Update uclouvain/openjpeg#826
Also correct names for data of issue uclouvain/openjpeg#823

Add test for issue 826

---

tests/nonregression/CMakeLists.txt
tests/nonregression/test_suite.ctest.in

Add test for issue 820

---

src/bin/jp2/opj_decompress.c
src/lib/openjp2/dwt.c
src/lib/openjp2/j2k.c
src/lib/openjp2/openjpeg.c
src/lib/openjp2/opj_includes.h
src/lib/openjp2/t1.c
src/lib/openjp2/thread.c

Fix warnings introduced by uclouvain/openjpeg#786

Fix some warnings

---

src/lib/openjp2/dwt.c
src/lib/openjp2/pi.c
src/lib/openjp2/t1.c

See
https://pdfium.googlesource.com/pdfium/+/b20ab6c7acb3be1393461eb650ca8fa4660c937e/third_party/libopenjpeg20/0020-opj_aligned_malloc.patch

Add overflow checks for opj_aligned_malloc

---

src/bin/jp2/convertbmp.c

Fix https://github.com/uclouvain/openjpeg/issues/833
Add some overflow check operations.

Fix issue 833.

---

doc/Doxyfile.dox.cmake.in

Some obsolete doxygen-1.8.9.1 tags are removed

Some Doxygen tags are removed

---

src/bin/jp2/convert.c

Changes in pnmtoimage if image data are missing

---

src/bin/common/color.c

Derived from a patch by Thuan Pham

color_apply_icc_profile: avoid potential heap buffer overflow

---

src/bin/jpwl/convert.c

Fix buffer overflow reading an image file less than four characters

---

NEWS.md

Fix year in NEWS

---

src/bin/jp2/converttif.c

Remove duplicate assignments in function tiftoimage

---

src/bin/jp2/opj_compress.c
src/bin/jp2/opj_decompress.c
src/bin/jp2/opj_dump.c

Includes the fix for CVE-2021-29338
Credit to @kaniini based on #1346
Fixes #1338

Fix integer overflow in num_images

---

CMakeLists.txt
INSTALL.md

They are supported on all platforms

Always install pkgconfig files

---

.github/workflows/build.yml

See https://github.com/softprops/action-gh-release/releases

Updated softprops/action-gh-release to v2
